### ISSUE TITLE
./docker/bootstrap　　でバグる

### ISSUE THREAD

**Issue by ghost** [hayashi-seiya/d_remarkable#2]
```
$ ./docker/bootstrap
-bash: ./docker/bootstrap: No such file or directory
```
こうなる

**Comment by seyayase** [comment]
どこのディレクトリでコマンド実行していますか？

実行したコマンドは、
`今いるディレクトリ/docker/bootstrap` というファイルの中身を実行してください
という意味なので
d_remarkableのディレクトリに移動して叩いてもらえると🙏

**Comment by ghost** [comment]
できました。

**Comment by seyayase** [comment]
よかったです 👌 
こちらcloseしちゃいますね🙏
